### ISSUE TITLE
Python example 1.3.0 cannot run on Ubuntu16.04

### ISSUE THREAD

**Issue by RSPwFPGAs** [OPAE/opae-sdk#1503]
Hi maintainer,

I am trying the Python Binding. I followed the [Example Installation](https://opae.github.io/1.3.0/docs/README.html#example-installation), and installed the .deb files with dpkg before the pip install.
After that, I tried to run the Python [Example Scripts](https://opae.github.io/1.3.0/docs/README.html#example-scripts), but got the following error:

>   ```bash
>user@ubuntu1604-opae-vfpga:~$ python3 opae-pybinding/hello_fpga.py 
>Traceback (most recent call last):
>  File "opae-pybinding/hello_fpga.py", line 2, in <module>
>    from opae import fpga
>  File "/home/user/.local/lib/python3.5/site-packages/opae/fpga/__init__.py", line 1, in <module>
>    from _opae import (
>ImportError: No module named '_opae'
> ```

I checked my pip install and it looked like this:
>```bash
>user@ubuntu1604-opae-vfpga:~$ pip3 list
>Package             Version               
>------------------- ----------------------
>chardet             2.3.0                 
>command-not-found   0.3                   
>language-selector   0.1                   
>opae.fpga           1.3.0                 
>pip                 20.0.2                
>pybind11            2.4.3                 
>pycurl              7.43.0                
>pygobject           3.20.0                
>python-apt          1.1.0b1+ubuntu0.16.4.5
>python-debian       0.1.27                
>python-systemd      231                   
>requests            2.9.1                 
>setuptools          20.7.0                
>six                 1.10.0                
>ssh-import-id       5.5                   
>ufw                 0.35                  
>unattended-upgrades 0.1                   
>urllib3             1.13.1                
>wheel               0.29.0
>```

I checked my environment and it looked like this:
>```bash
>user@ubuntu1604-opae-vfpga:~$ tree /home/user/.local/lib/python3.5/site-packages/ -L 3
>/home/user/.local/lib/python3.5/site-packages/
>├── opae
>│   ├── fpga
>│   │   ├── __init__.py
>│   │   ├── _opae.cpython-35m-x86_64-linux-gnu.so
>│   │   └── __pycache__
>│   ├── __init__.py
>│   └── __pycache__
>│       └── __init__.cpython-35.pyc
>├── opae.fpga-1.3.0.dist-info
>│   ├── DESCRIPTION.rst
>│   ├── entry_points.txt
>│   ├── INSTALLER
>│   ├── METADATA
>│   ├── metadata.json
>│   ├── RECORD
>│   ├── top_level.txt
>│   └── WHEEL
>```

> ```bash
>user@ubuntu1604-opae-vfpga:~$ ls /usr/local/lib/
>libbmc.so        libhssi-io.so        libopae-c-ase.so        libopae-c++-nlb.so        libopae-c.so        libopae-c++-utils.so        libopae-cxx-core.so  python2.7
>libbmc.so.1      libhssi-io.so.1      libopae-c-ase.so.1      libopae-c++-nlb.so.1      libopae-c.so.1      libopae-c++-utils.so.1      libsafestr.a         python3.5
>libbmc.so.1.3.0  libhssi-io.so.1.3.0  libopae-c-ase.so.1.3.0  libopae-c++-nlb.so.1.3.0  libopae-c.so.1.3.0  libopae-c++-utils.so.1.3.0  libxfpga.so
>```

**Comment by RSPwFPGAs** [comment]
This solved it:
export PYTHONPATH=/home/user/.local/lib/python3.5/site-packages/opae/fpga
