### ISSUE TITLE
'install' build target is no longer an install target

### ISSUE THREAD

**Issue by chipb** [OPAE/opae-sdk#1933]
```sh
ccbilbre@ccbilbre-mobl2:~/src/opae-sdk$ cmake -DCMAKE_INSTALL_PREFIX=/home/ccbilbre/opae -B build >/dev/null 2>&1
ccbilbre@ccbilbre-mobl2:~/src/opae-sdk$ make -C build -j8 install >/dev/null 2>&1
ccbilbre@ccbilbre-mobl2:~/src/opae-sdk$ ~/opae/bin/PACSign --help
Traceback (most recent call last):
  File "/home/ccbilbre/opae/bin/PACSign", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3254, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3237, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3266, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pacsign==1.0.3' distribution was not found and is required by the application
```

If a script lands in `bin/` after `make install`, it should execute from that location.

**Comment by chipb-intel** [comment]
I guess in theory custom wrapper scripts (replacing or modifying the setuptools ones) could be used to extend `PYTHONPATH` into the prefix location before they import the entry point module. But that's even weirder than expecting `make install` can usefully install a Python package in an arbitrary location.

The recommendation should just probably be either one of:
- Manually extend `PYTHONPATH` to include the prefix path
- Disable installation of these tools when building OPAE (so the incomplete wrappers aren't installed to $PREFIX/bin) and manually install the Python-based tools to a virtual env for use

One could argue the user shouldn't care what language was used to implement any tool; they just expect `make install` to follow standard conventions. The workaround is simple enough that it's not worth the pain of fighting Python packaging gunk though.
